<?php
  
error_reporting(E_ALL);
ini_set('display_errors', 1);

?><div>
  <div class="inputs">
    <div id="csseditor_site">
      <?php
/*
        echo $this->siteSelect(array('site'), [
            'empty_option' => $this->translate('Default'),
        ]);
*/
      ?>
    </div>
    <div>
      <?php // echo $this->formTextarea($textarea); ?>
    </div>
    <div>
      <?php echo $this->translate('Please type the pdf2text path with trailing slash.'); ?>
      <?php echo $this->formText($formtext); ?>      
    </div>
    
  </div>
    
<br/><br/>
<!--<a class="button" id="save">Save</a>-->
<!--<a class="button" id="restore">Restore</a>-->

</span>

</div>

