<?php
$escape = $this->plugin('escapeHtml');
$this->htmlElement('html')->setAttribute('lang', $this->lang());
$this->headMeta()->setCharset('utf-8');
$this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1');
$this->headTitle($this->setting('installation_title', 'Omeka S'))->setSeparator(' · ');
$this->headLink()->prependStylesheet($this->assetUrl('css/style.css'));
$this->headLink()->prependStylesheet($this->assetUrl('css/iconfonts.css', 'Omeka'));
$this->headLink()->prependStylesheet($this->assetUrl('vendor/tablesaw/tablesaw.stackonly.css', 'Omeka'));
$this->headScript()->prependFile($this->assetUrl('js/default.js'));
$this->headScript()->prependFile($this->assetUrl('js/global.js', 'Omeka'));
$this->headScript()->prependFile($this->assetUrl('vendor/tablesaw/tablesaw.stackonly.jquery.js', 'Omeka'));
$this->headScript()->prependFile($this->assetUrl('vendor/jquery/jquery.min.js', 'Omeka'));
$this->trigger('view.layout');
$title = $this->pageTitle($site->title());
$logo = $this->themeSettingAssetUrl('logo');
$bg = $this->themeSettingAssetUrl('background_image');
$bgStyle = $this->themeSetting('background_layout');
if ($logo):
    $title = '<img src="' . $this->escapeHtml($logo) . '">';
endif;
$userBar = $this->userBar();
?>
<?php echo $this->doctype(); ?>
<?php echo $this->htmlElement('html'); ?>
    <head>
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle(); ?>
        <?php echo $this->headLink(); ?>
        <?php echo $this->headStyle(); ?>
        <style>
        <?php if ($bg): ?>
          body {
            background: url(<?php echo $this->escapeHtml($bg); ?>);
            <?php if (isset($bgStyle) && ($bgStyle !== 'tile')): ?>
            background-repeat: no-repeat;
            background-size: <?php echo $bgStyle; ?>;
            background-attachment: fixed;
            <?php endif; ?>
          }
        <?php endif; ?>

        <?php if ($headerColor = $this->themeSetting('header_color')): ?>
        .site-title {
          background-color: <?php echo $headerColor; ?>;
        }
        <?php endif; ?>
        
        <?php if ($buttonColor = $this->themeSetting('button_color')): ?>
        buttton,
        .button,
        [type="submit"],
        .toc-block > ul > li {
          background-color: <?php echo $buttonColor; ?>;
        }
        <?php endif; ?>
        
        <?php if ($linkColor = $this->themeSetting('link_color')): ?>
        a:link,
        a:visited {
          color: <?php echo $linkColor; ?>;
        }
        <?php endif; ?>
        </style>
        <?php echo $this->headScript(); ?>
    </head>

    <?php echo $this->htmlElement('body'); ?>
        <?php echo $userBar; ?>
        <header class="site-header" role="banner">
            <div class="wrapper">
                <?php if ($this->themeSetting('logo')): ?>
                <a href="<?php echo $site->url(); ?>" class="site-title logo"><img src="<?php echo $this->themeSettingAssetUrl('logo'); ?>" title="Logo"></a>
                <?php else: ?>
                <a href="<?php echo $site->url(); ?>" class="site-title"><?php echo $site->title(); ?></a>
                <?php endif; ?>
    
                <nav class="site-nav">
                    <input type="checkbox" id="nav-trigger" class="nav-trigger" aria-label="<?php echo $this->translate('Toggle menu'); ?>"/>
                    <label for="nav-trigger">
                        <span class="menu-icon"></span>
                    </label>

                    <div class="trigger">
                    <?php
                    echo $site->publicNav()->menu()->renderMenu(null, [
                        'maxDepth' => $this->themeSetting('nav_depth') - 1
                    ]);
                    ?>
                    </div>
                </nav>
            </div>
        </header>
        <main class="page-content" aria-label="<?php echo $this->escapeHtml($this->translate('Content')); ?>">
            <div class="wrapper">
            <?php echo $this->content; ?>
            </div>
        </main>
        <footer class="site-footer h-card">
            <div class="wrapper">	
                <?php if ($footerContent = $this->themeSetting('footer')): ?>
                <?php echo $footerContent; ?>
                <?php else: ?>
                <?php echo $this->translate('Powered by Omeka S'); ?>
                <?php endif; ?>
            </div>
        </footer>
    </body>
</html>
