<?php
$translate = $this->plugin('translate');
$prevText = $translate('Prev');
$nextText = $translate('Next');
?>
<?php if ($prevPage || $nextPage): ?>
<div class="site-page-pagination">
    <?php echo $prevPage ? $this->hyperlink($prevText, $prevPage->siteUrl(), ['class' => 'yellow button']) : ''; ?>
    <?php echo $nextPage ? $this->hyperlink($nextText, $nextPage->siteUrl(), ['class' => 'yellow button']): ''; ?>
</div>
<?php endif; ?>