# This is a basic workflow to help you get started with Actions

name: Deploy

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: pxgamer/composer-action@v2.1.0
        with:
          command: install --no-dev --ignore-platform-reqs --no-interaction --no-suggest --no-progress --optimize-autoloader --prefer-dist
      - uses: disorientations/rsync-deployments@master
        with:
          USER_AND_HOST: disorie1@disorientations.org
          DEST: /home/disorie1/public_html/
          RSYNC_OPTIONS: -avzr --delete --exclude /config/database.ini --exclude /uploads/
        env: 
          DEPLOY_KEY: ${{secrets.DEPLOY_KEY}} 
